all:
  vars:
    ansible_connection: network_cli
    ansible_user: "{{ lookup('env', 'NETAUTO_USER') | default('netauto', true) }}"
    ansible_password: "{{ lookup('env', 'NETAUTO_PASS') }}"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: "{{ lookup('env', 'NETAUTO_ENABLE') }}"

  children:
    cisco_ios:
      vars:
        ansible_network_os: ios
      hosts:
        hyd-edge-01: { ansible_host: 10.10.1.11 }
        hyd-edge-02: { ansible_host: 10.10.1.12 }
    cisco_xr:
      vars:
        ansible_network_os: iosxr
      hosts:
        hyd-core-01: { ansible_host: 10.10.1.21 }
    cisco_nxos:
      vars:
        ansible_network_os: nxos
      hosts:
        blr-spine-01: { ansible_host: 10.20.1.41 }
        blr-spine-02: { ansible_host: 10.20.1.42 }
    arista_eos:
      vars:
        ansible_network_os: eos
      hosts:
        hyd-tor-01: { ansible_host: 10.10.1.31 }
    juniper_junos:
      vars:
        ansible_network_os: junos
        ansible_connection: netconf
      hosts:
        blr-edge-01: { ansible_host: 10.20.1.11 }
        blr-core-01: { ansible_host: 10.20.1.21 }

    edges:
      hosts:
        hyd-edge-01: {}
        hyd-edge-02: {}
        blr-edge-01: {}
