"""Configuration diff helpers."""

from __future__ import annotations

import difflib
import re

# Lines that should be stripped before diffing because they change every show run
# without representing a real configuration change.
_NOISE_PATTERNS = [
    re.compile(r"^!\s*Last configuration change.*$"),
    re.compile(r"^!\s*NVRAM config last updated.*$"),
    re.compile(r"^!\s*Time:.*$"),
    re.compile(r"^Building configuration\.\.\.$"),
    re.compile(r"^Current configuration\s*:.*$"),
    re.compile(r"^!\s*No configuration change since last restart$"),
    re.compile(r"^!\s*Generated by .* on .*$"),
]


def _strip_noise(text: str) -> list[str]:
    out: list[str] = []
    for raw in text.splitlines():
        line = raw.rstrip()
        if any(p.match(line) for p in _NOISE_PATTERNS):
            continue
        out.append(line)
    return out


def unified_config_diff(
    before: str,
    after: str,
    *,
    fromfile: str = "before",
    tofile: str = "after",
    context: int = 3,
) -> str:
    """Return a unified diff between two configuration blobs.

    Volatile lines (timestamps, "Building configuration...", etc.) are removed
    from both inputs prior to diffing so that benign cosmetic changes don't
    surface as false positives. An empty string is returned if the
    configurations are functionally identical.
    """
    a = _strip_noise(before)
    b = _strip_noise(after)
    if a == b:
        return ""
    return "\n".join(
        difflib.unified_diff(a, b, fromfile=fromfile, tofile=tofile, n=context, lineterm="")
    )
